### ISSUE TITLE
Play button not passing through

### ISSUE THREAD

**Issue by CasaPas** [xthursdayx/docker-gpodder#1]
Platform: qNAP (Installation)
Access: Web gui on local network from Safari based on an iMac.

Install wen't perfectly, no issues.
Can access the container no problem
Once some files are added, the play function does nothing on my local machine.

Do I need to add any environment settings?

**Comment by xthursdayx** [comment]
Hi, sorry for the delayed response. To be honest, I only use this container to download podcasts, not for playback, so I haven't messed with the play function at all. I will look into it and, hopefully, report back soon.

**Comment by xthursdayx** [comment]
So, after discussing with the developer of the GuacGUI baseimage I use for this container ([see conversation here](https://github.com/linuxserver/docker-baseimage-guacgui/issues/26)), it seems that at this point there are too many audio performance issues with xrdp to get it to work well. I will continue to monitor the situation in case this changes, but for now I think it will be best just to use gPodder as a podcatcher rather than a player. Sorry about that.
