### ISSUE TITLE
Possible to implement ffmpeg?

### ISSUE THREAD

**Issue by viktorrauch** [xthursdayx/docker-gpodder#18]
Hi there,

first of all: Thank you for your docker image!
It helps me to manage all my youtube playlists I follow in Plex.

Sadly many of those subscriptions are only downloading in 720p because it isn't able to merge best video with best audio.
Is it possible for you to implement ffmpeg into the docker image so all the videos downloaded with youtube-dl are able to be muxed?

**Comment by xthursdayx** [comment]
Hi, ffmpeg is actually already included within the docker image. Are you seeing a log or something that led you to believe that ffmpeg being missing is the cause of the problem?  If I remember correctly, GPodder wouldn't be able to download and mux videos at all without ffmpeg, though to be honest, it's been a while since I set everything up to allow for downloading YouTube playlists. I assume that you've already edited the youtube.* preferences in the config, right?
